# Generated by Django 5.1.4 on 2025-01-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ItemNo', models.CharField(max_length=255)),
                ('colorVariants', models.JSONField(blank=True, default=list)),
                ('noos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='colorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=255)),
                ('colorCode', models.CharField(max_length=255)),
                ('variant_details', models.JSONField(blank=True, default=list)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='noos.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarcodeNo', models.IntegerField(blank=True, null=True, verbose_name='BarcodeNo')),
                ('size', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('colorVariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_variants', to='noos.colorvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noos.store')),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='noos.variant')),
            ],
            options={
                'unique_together': {('store', 'variant')},
            },
        ),
    ]
