# Generated by Django 5.1.4 on 2025-01-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('itemNo', models.CharField(max_length=255)),
                ('product_description', models.TextField(default='No description added')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='colorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=255)),
                ('colorCode', models.CharField(max_length=50)),
                ('noos', models.BooleanField(default=False)),
                ('image_urls', models.JSONField(default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='noos.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BarcodeNo', models.BigIntegerField(default=0)),
                ('size', models.CharField(max_length=50)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('colorVariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='noos.colorvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noos.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noos.variant')),
            ],
        ),
    ]
