# Generated by Django 5.1.4 on 2025-01-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Inventory',
        ),
    ]
