# Generated by Django 5.1.4 on 2025-01-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos', '0002_rename_stock_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='noos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('store', 'product')},
        ),
    ]
