# Generated by Django 5.1.4 on 2025-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos', '0003_rename_stock_inventory_quantity_product_noos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BarcodeNo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
